### ISSUE TITLE
Add a slider to control the delay after picking the second card before the cards flip back over

### ISSUE THREAD

**Issue by precurejunkie** [Kanmuri/kanjipairs_html#1]
My kana reading is sometimes a little on the slow side, depending on the kana, and every so often I hit a card that I don't finish reading the kana before it flips back over.  For someone who reads fast, it would be painful to make it wait longer, so a preference or a control for it would be cool.

**Comment by Kanmuri** [comment]
Sounds good. What do you think would be a reasonable upper bound on the wait time range?

**Comment by precurejunkie** [comment]
hmm, 30 seconds would be WAY too long.  Maybe between 1 and 10?  10 seconds would probably be on the long side.  5 would be plenty for me, but there's probably other people that read slower than me if they're new at it :)

**Comment by Kanmuri** [comment]
This has been added, though it will default to 2 seconds each time the page is loaded.
There's a TODO to look into the possibility of storing that value on the client between runs.
